// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperProjectPE.DAO;

#nullable disable

namespace SuperProjectPE.DAO.Migrations
{
    [DbContext(typeof(SilverJewelry2023DbContext))]
    [Migration("20241114163850_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperProjectPE.BO.BranchAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("AccountPassword")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.HasKey("AccountId")
                        .HasName("PK__BranchAc__349DA586C609B6BD");

                    b.HasIndex(new[] { "EmailAddress" }, "UQ__BranchAc__49A14740B3483417")
                        .IsUnique()
                        .HasFilter("[EmailAddress] IS NOT NULL");

                    b.ToTable("BranchAccount", (string)null);
                });

            modelBuilder.Entity("SuperProjectPE.BO.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FromCountry")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__19093A0B9DB2A055");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("SuperProjectPE.BO.SilverJewelry", b =>
                {
                    b.Property<string>("SilverJewelryId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("MetalWeight")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<string>("SilverJewelryDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SilverJewelryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SilverJewelryId")
                        .HasName("PK__SilverJe__1F12719775E48DD4");

                    b.HasIndex("CategoryId");

                    b.ToTable("SilverJewelry", (string)null);
                });

            modelBuilder.Entity("SuperProjectPE.BO.SilverJewelry", b =>
                {
                    b.HasOne("SuperProjectPE.BO.Category", "Category")
                        .WithMany("SilverJewelries")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__SilverJew__Categ__29572725");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SuperProjectPE.BO.Category", b =>
                {
                    b.Navigation("SilverJewelries");
                });
#pragma warning restore 612, 618
        }
    }
}
